import { NextResponse } from "next/server"
import { sql, initDb } from "@/lib/db"
import { requireUser } from "@/lib/api-auth"
import { apiError } from "@/lib/errors"
import { rateLimited, keyFrom } from "@/lib/rate-limit"
import {
  transitionAlert, coerceAlertId, addAlertNote, assignAlert, bulkTransition,
  SUPPRESSION_REASONS, type AlertState,
} from "@/lib/exposure/alert-workflow"
import { telegramConfigured } from "@/lib/notify/telegram-adapter"
import { ticketProvider } from "@/lib/ticketing"

/**
 * SOC alerts generated by Exposure Intelligence.
 *
 * Read-and-triage only: alerts are CREATED by the refresh pipeline
 * (`refreshAsset` → correlation → RBVM → `evaluateAlerts`), never by an HTTP
 * caller. There is no endpoint that can manufacture an alert, and none that can
 * set a state the lifecycle does not permit.
 *
 * GET  -> alerts (filterable, paginated) plus counts and integration status
 * POST -> analyst transition, validated server-side against the state machine
 */

/** Upper bound on one batch — keeps a single request inside the function's time budget. */
const BULK_LIMIT = 100

const VALID_STATES: ReadonlySet<string> = new Set([
  "open", "acknowledged", "in_progress", "resolved", "closed", "suppressed",
])
const MAX_LIMIT = 200

export async function GET(req: Request) {
  const gate = await requireUser(req)
  if (gate.deny) return gate.deny
  try {
    await initDb()
    const url = new URL(req.url)

    // Every filter is validated here; a client value is never interpolated.
    const state = url.searchParams.get("state")?.trim().toLowerCase()
    const severity = url.searchParams.get("severity")?.trim().toLowerCase()
    const evidence = url.searchParams.get("evidence")?.trim().toLowerCase()
    const notification = url.searchParams.get("notification")?.trim().toLowerCase()
    const ticket = url.searchParams.get("ticket")?.trim().toLowerCase()

    const stateFilter = state && VALID_STATES.has(state) ? state : null
    const severityFilter = severity && ["critical", "high", "medium", "low"].includes(severity) ? severity : null
    const evidenceFilter = evidence && ["confirmed", "strong", "product", "weak", "pivot"].includes(evidence) ? evidence : null
    const notifyFilter = notification && ["pending", "sent", "failed", "retrying", "disabled"].includes(notification) ? notification : null
    const ticketFilter = ticket && ["none", "pending", "open", "updated", "closed", "failed"].includes(ticket) ? ticket : null

    const limitRaw = Number(url.searchParams.get("limit"))
    const limit = Number.isFinite(limitRaw) && limitRaw > 0 ? Math.min(Math.floor(limitRaw), MAX_LIMIT) : 50
    const offsetRaw = Number(url.searchParams.get("offset"))
    const offset = Number.isFinite(offsetRaw) && offsetRaw > 0 ? Math.floor(offsetRaw) : 0

    // `activeOnly` is the default view: what needs attention now.
    const activeOnly = !stateFilter

    const alerts = (await sql`
      SELECT id, fingerprint, asset_key, port, cve_id, kind, state, severity,
             assigned_to, assigned_at,
             risk_score, previous_risk, evidence_tier, payload,
             notification_state, notify_attempts, notify_last_error, notified_at,
             notified_severity, notified_risk, escalation_count,
             ticket_state, ticket_provider, ticket_key, ticket_url, ticket_last_error,
             suppressed_reason, suppressed_by, suppressed_until,
             created_at, updated_at, acknowledged_at, started_at, resolved_at, closed_at
      FROM exposure_alerts
      WHERE user_id = ${gate.user.id}
        AND (${stateFilter}::text IS NULL OR state = ${stateFilter})
        AND (${activeOnly} = false OR state IN ('open','acknowledged','in_progress'))
        AND (${severityFilter}::text IS NULL OR severity = ${severityFilter})
        AND (${evidenceFilter}::text IS NULL OR evidence_tier = ${evidenceFilter})
        AND (${notifyFilter}::text IS NULL OR notification_state = ${notifyFilter})
        AND (${ticketFilter}::text IS NULL OR ticket_state = ${ticketFilter})
      ORDER BY
        CASE severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
        created_at DESC
      LIMIT ${limit} OFFSET ${offset}
    `) as Array<Record<string, unknown>>

    const totalRows = (await sql`
      SELECT count(*)::int AS n FROM exposure_alerts
      WHERE user_id = ${gate.user.id}
        AND (${stateFilter}::text IS NULL OR state = ${stateFilter})
        AND (${activeOnly} = false OR state IN ('open','acknowledged','in_progress'))
        AND (${severityFilter}::text IS NULL OR severity = ${severityFilter})
        AND (${evidenceFilter}::text IS NULL OR evidence_tier = ${evidenceFilter})
        AND (${notifyFilter}::text IS NULL OR notification_state = ${notifyFilter})
        AND (${ticketFilter}::text IS NULL OR ticket_state = ${ticketFilter})
    `) as Array<{ n: number }>

    const byState = (await sql`SELECT state, count(*)::int AS n FROM exposure_alerts WHERE user_id = ${gate.user.id} GROUP BY state`) as Array<{ state: string; n: number }>
    const bySeverity = (await sql`
      SELECT severity, count(*)::int AS n FROM exposure_alerts
      WHERE user_id = ${gate.user.id} AND state IN ('open','acknowledged','in_progress') GROUP BY severity
    `) as Array<{ severity: string; n: number }>
    const byNotification = (await sql`SELECT notification_state, count(*)::int AS n FROM exposure_alerts WHERE user_id = ${gate.user.id} GROUP BY notification_state`) as Array<{ notification_state: string; n: number }>

    const provider = ticketProvider()
    return NextResponse.json({
      // Normalised at the boundary so the client receives the `number` its type
      // declares. Alert ids are far below 2^53, so the narrowing is lossless.
      alerts: alerts.map((a) => ({ ...a, id: Number(a.id) })),
      total: totalRows[0]?.n ?? 0,
      limit, offset,
      counts: {
        state: Object.fromEntries(byState.map((c) => [c.state, c.n])),
        severity: Object.fromEntries(bySeverity.map((c) => [c.severity, c.n])),
        notification: Object.fromEntries(byNotification.map((c) => [c.notification_state, c.n])),
      },
      // Integration status is reported honestly so the UI never implies a
      // message was delivered or a ticket exists when neither is configured.
      integrations: {
        telegramConfigured: telegramConfigured(),
        ticketProvider: provider.name,
        ticketingConfigured: provider.configured,
      },
      suppressionReasons: SUPPRESSION_REASONS,
    }, { headers: { "Cache-Control": "private, max-age=10" } })
  } catch (e) {
    return apiError(e, "exposure-alerts")
  }
}

export async function POST(req: Request) {
  const gate = await requireUser(req)
  if (gate.deny) return gate.deny
  const denied = rateLimited(keyFrom(req, gate.user.id), 60, 60_000)
  if (denied) return denied

  try {
    const body = (await req.json().catch(() => null)) as {
      id?: unknown; ids?: unknown; action?: unknown; assignee?: unknown
      state?: unknown; reason?: unknown; note?: unknown; suppressedUntil?: unknown
    } | null

    const action = typeof body?.action === "string" ? body.action : ""

    // ── Analyst note ──────────────────────────────────────────────────────
    // The state machine records what changed; a note records why, which is the
    // part that carries the analyst's judgement and the part the next person on
    // the queue actually needs.
    if (action === "note") {
      const noteId = coerceAlertId(body?.id)
      if (noteId === null) return NextResponse.json({ error: "A positive numeric 'id' is required." }, { status: 400 })
      const text = typeof body?.note === "string" ? body.note : ""
      const r = await addAlertNote(noteId, gate.user.id, gate.user.id, text)
      if (!r.ok) {
        return NextResponse.json({ error: r.error, code: r.code }, { status: r.code === "not_found" ? 404 : 400 })
      }
      return NextResponse.json({ ok: true, id: noteId })
    }

    // ── Assignment ────────────────────────────────────────────────────────
    if (action === "assign" || action === "unassign") {
      const aid = coerceAlertId(body?.id)
      if (aid === null) return NextResponse.json({ error: "A positive numeric 'id' is required." }, { status: 400 })
      // Only ever the authenticated user or nobody. Accepting an arbitrary
      // assignee string would let one user write another's name into an audit
      // record they do not control.
      const assignee = action === "assign" ? gate.user.id : null
      const r = await assignAlert(aid, gate.user.id, gate.user.id, assignee)
      if (!r.ok) return NextResponse.json({ error: r.error, code: r.code }, { status: 404 })
      return NextResponse.json({ ok: true, id: aid, assignedTo: assignee })
    }

    // ── Bulk transition ───────────────────────────────────────────────────
    // A queue is triaged in batches. Reported per id rather than as a count,
    // because "37 of 40 applied" without saying which three failed is not
    // actionable.
    if (Array.isArray(body?.ids)) {
      const ids = (body.ids as unknown[]).map(coerceAlertId).filter((n): n is number => n !== null)
      if (!ids.length) return NextResponse.json({ error: "'ids' contained no valid alert id." }, { status: 400 })
      if (ids.length > BULK_LIMIT) {
        return NextResponse.json(
          { error: `At most ${BULK_LIMIT} alerts can be actioned at once.` },
          { status: 400 },
        )
      }
      const bulkState = typeof body?.state === "string" ? body.state.trim().toLowerCase() : ""
      if (!VALID_STATES.has(bulkState)) {
        return NextResponse.json({ error: `'state' must be one of: ${[...VALID_STATES].join(", ")}.` }, { status: 400 })
      }
      const result = await bulkTransition({
        alertIds: ids,
        userId: gate.user.id,
        to: bulkState as AlertState,
        actor: gate.user.id,
        reason: typeof body?.reason === "string" ? body.reason.trim().toLowerCase() : null,
        note: typeof body?.note === "string" ? body.note.slice(0, 4000) : null,
      })
      return NextResponse.json({ ...result, requested: ids.length })
    }

    // Nothing from the client is trusted: the id must be numeric, the target
    // state must be known, and the transition itself is validated server-side.
    const id = coerceAlertId(body?.id)
    const state = typeof body?.state === "string" ? body.state.trim().toLowerCase() : ""

    if (id === null || id <= 0) return NextResponse.json({ error: "A positive numeric 'id' is required." }, { status: 400 })
    if (!VALID_STATES.has(state)) {
      return NextResponse.json({ error: `'state' must be one of: ${[...VALID_STATES].join(", ")}.` }, { status: 400 })
    }

    const result = await transitionAlert({
      alertId: id,
      // Tenant of the acting session — an alert outside it reads as not found.
      userId: gate.user.id,
      to: state as AlertState,
      // The actor is the authenticated user — never a client-supplied name.
      actor: gate.user.id,
      reason: typeof body?.reason === "string" ? body.reason.trim().toLowerCase() : null,
      note: typeof body?.note === "string" ? body.note.slice(0, 500) : null,
      suppressedUntil: typeof body?.suppressedUntil === "string" ? body.suppressedUntil : null,
    })

    if (!result.ok) {
      const status = result.code === "not_found" ? 404 : result.code === "reason_required" ? 400 : 409
      return NextResponse.json({ error: result.error, code: result.code }, { status })
    }
    return NextResponse.json({ id, from: result.from, to: result.to })
  } catch (e) {
    return apiError(e, "exposure-alerts")
  }
}
